#include "pomp_lib.h"

struct ompregdescr omp_rd_27 = {
  "parallelfor", "", 0, "ballAlg-omp.c", 111, 111, 115, 115
};

#define POMP_DLIST_00027 shared(omp_rd_27)

struct ompregdescr omp_rd_28 = {
  "parallelfor", "", 0, "ballAlg-omp.c", 126, 126, 144, 144
};

#define POMP_DLIST_00028 shared(omp_rd_28)

struct ompregdescr omp_rd_29 = {
  "parallelfor", "", 0, "ballAlg-omp.c", 612, 612, 617, 617
};

#define POMP_DLIST_00029 shared(omp_rd_29)

struct ompregdescr omp_rd_30 = {
  "parallelfor", "", 0, "ballAlg-omp.c", 627, 627, 632, 632
};

#define POMP_DLIST_00030 shared(omp_rd_30)

